# DataPreprocessing

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
data = pd.read_json('intents.json')

In [4]:
data.head()

                                             intents
0  {'tag': 'greetings', 'patterns': ['Hello', 'Hi...
1  {'tag': 'deepfake_identification', 'patterns':...
2  {'tag': 'deepfake_detection_signs', 'patterns'...
3  {'tag': 'deepfake_detection_tools', 'patterns'...
4  {'tag': 'deepfake_impact', 'patterns': ['How d...

In [5]:
data.shape

(51, 1)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 0 to 50
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   intents  51 non-null     object
dtypes: object(1)
memory usage: 816.0+ bytes

In [7]:
df = data.dropna()

In [8]:
df.isnull().sum()

intents    0
dtype: int64

In [9]:
df.info

<bound method DataFrame.info of                                               intents
0   {'tag': 'greetings', 'patterns': ['Hello', 'Hi...
1   {'tag': 'deepfake_identification', 'patterns':...
2   {'tag': 'deepfake_detection_signs', 'patterns'...
3   {'tag': 'deepfake_detection_tools', 'patterns'...
4   {'tag': 'deepfake_impact', 'patterns': ['How d...
5   {'tag': 'deepfake_legal_aspects', 'patterns': ...
6   {'tag': 'deepfake_detection_reliability', 'pat...
7   {'tag': 'deepfake_use_cases', 'patterns': ['Wh...
8   {'tag': 'deepfake_future', 'patterns': ['What ...
9   {'tag': 'deepfake_education', 'patterns': ['Ho...
10  {'tag': 'deepfake_media_literacy', 'patterns':...
11  {'tag': 'deepfake_research', 'patterns': ['Wha...
12  {'tag': 'deepfake_digital_forensics', 'pattern...
13  {'tag': 'deepfake_benefits', 'patterns': ['Wha...
14  {'tag': 'deepfake_ethical_concerns', 'patterns...
15  {'tag': 'deepfake_media_regulation', 'patterns...
16  {'tag': 'deepfake_video_examples', 'patterns':...
17  {'tag': 'deepfake_technology_history', 'patter...
18  {'tag': 'deepfake_impact_on_journalism', 'patt...
19  {'tag': 'deepfake_detection_future', 'patterns...
20  {'tag': 'deepfake_public_perception', 'pattern...
21  {'tag': 'deepfake_speech_synthesis', 'patterns...
22  {'tag': 'deepfake_detection_tools', 'patterns'...
23  {'tag': 'deepfake_industry_impact', 'patterns'...
24  {'tag': 'deepfake_social_media', 'patterns': [...
25  {'tag': 'deepfake_protection_measures', 'patte...
26  {'tag': 'deepfake_case_studies', 'patterns': [...
27  {'tag': 'deepfake_technology_education', 'patt...
28  {'tag': 'deepfake_and_artificial_intelligence'...
29  {'tag': 'deepfake_prevention_technology', 'pat...
30  {'tag': 'deepfake_legal_implications', 'patter...
31  {'tag': 'deepfake_authentication', 'patterns':...
32  {'tag': 'deepfake_research', 'patterns': ['Wha...
33  {'tag': 'deepfake_ethics', 'patterns': ['What ...
34  {'tag': 'deepfake_social_implications', 'patte...
35  {'tag': 'deepfake_misinformation', 'patterns':...
36  {'tag': 'deepfake_technology_limitations', 'pa...
37  {'tag': 'deepfake_community_responses', 'patte...
38  {'tag': 'deepfake_future_trends', 'patterns': ...
39  {'tag': 'deepfake_fraud', 'patterns': ['How ca...
40  {'tag': 'deepfake_technology_legislation', 'pa...
41  {'tag': 'deepfake_detection_tools', 'patterns'...
42  {'tag': 'deepfake_legal_implications', 'patter...
43  {'tag': 'deepfake_in_entertainment', 'patterns...
44  {'tag': 'deepfake_detection_challenges', 'patt...
45  {'tag': 'deepfake_prevention_methods', 'patter...
46  {'tag': 'deepfake_impact_on_journalism', 'patt...
47  {'tag': 'deepfake_security_measures', 'pattern...
48  {'tag': 'deepfake_tutorials', 'patterns': ['Ar...
49  {'tag': 'deepfake_impact_on_relationships', 'p...
50  {'tag': 'deepfake_use_in_politics', 'patterns'...>

In [10]:
df.columns

Index(['intents'], dtype='object')

In [11]:
df.size

51

In [12]:
df.describe()

                                                  intents
count                                                  51
unique                                                 51
top     {'tag': 'greetings', 'patterns': ['Hello', 'Hi...
freq                                                    1

In [13]:
df.head()

                                             intents
0  {'tag': 'greetings', 'patterns': ['Hello', 'Hi...
1  {'tag': 'deepfake_identification', 'patterns':...
2  {'tag': 'deepfake_detection_signs', 'patterns'...
3  {'tag': 'deepfake_detection_tools', 'patterns'...
4  {'tag': 'deepfake_impact', 'patterns': ['How d...

In [14]:
df.head()

                                             intents
0  {'tag': 'greetings', 'patterns': ['Hello', 'Hi...
1  {'tag': 'deepfake_identification', 'patterns':...
2  {'tag': 'deepfake_detection_signs', 'patterns'...
3  {'tag': 'deepfake_detection_tools', 'patterns'...
4  {'tag': 'deepfake_impact', 'patterns': ['How d...